#!/bin/bash

source activate AIADev

python ~/GitHub/JP2_Processing/test_NASM_jpeg2000_processing_.py 
# sleep 10
expect "WAVELENGTH: " {
	echo "193"
}

echo 2018
echo 1
echo 30
echo blah blah blah some text
echo some text
echo 
echo 128